display-name: 'Netherite Shield'
permission-node: 'none'
no-permission: '&cYou don''t have the permission to build Netherite Shield!'
smithing: true
features:
  unbreakable: false
  custom-model:
    enabled: false
    data: 1
  fire-proof: true
  fall-damage-mitigation: true
  fire-resistance: true
hide-attribute: false
attributes:
  ATTACK_DAMAGE: 2
  ATTACK_SPEED: -1.5
  MOVEMENT_SPEED: -0.02
  MAX_HEALTH: 4
crafting:
  enabled: false
  items:
    W:
    - ACACIA_PLANKS
    - BIRCH_PLANKS
    - CRIMSON_PLANKS
    - DARK_OAK_PLANKS
    - JUNGLE_PLANKS
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - WARPED_PLANKS
    N: NETHERITE_INGOT
  shape:
  - 'WNW'
  - 'WWW'
  - ' W '