display-name: 'Netherite Shield'
permission-node: 'none'
no-permission: '&cYou don''t have the permission to build Netherite Shield!'
smithing: true
crafting:
  enabled: false
  items:
    W:
    - ACACIA_PLANKS
    - BIRCH_PLANKS
    - CRIMSON_PLANKS
    - DARK_OAK_PLANKS
    - JUNGLE_PLANKS
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - WARPED_PLANKS
    N: NETHERITE_INGOT
  shape:
  - 'WNW'
  - 'WWW'
  - ' W '